baseURL = 'https://zoo-project.github.io/website/'
languageCode = 'en-us'
theme = 'zoo-project'

[params]
description = 'The ZOO-Project is an open source processing platform, released under MIT/X11 Licence. It provides the polyglot ZOO-Kernel, a server implementation of the Web Processing Service (WPS) (1.0.0 and 2.0.0) and the OGC API - Processes standards published by the OGC'

  # "relatedtext" is the text that appears above the tag list at the bottom of pages.
  relatedtext = "Related"
  favicon = "/favicon.ico"

  #list items
  datesinlist = true
  authorsinlist = true

  #footer items
  nextprev = true
  taglist = true
  showrss = true
  
# navigation menu
[menu]
     [[menu.main]]
      identifier = "index"
      name = "Index"
      url = "/"
      weight = 1

    [[menu.main]]
      identifier = "services"
       name = "Services"
       url = "/code/services/"
       parent = "code"
       weight = 2

    [[menu.main]]
      identifier = "about"
      name = "About"
      url = "#"
      weight = 3
      hasChildren = true

    [[menu.main]]
      identifier = "introduction"
      name = "Introduction"
      url = "https://zoo-project.github.io/docs/intro.html"
      parent = "about"
      weight = 1

     [[menu.main]]
      identifier = "tribe"
      name = "Tribe"
      url = "/about/tribe/"
      parent = "about"
      weight = 2

      [[menu.main]]
      identifier = "event"
      name = "Event"
      url = "/about/event/"
      parent = "about"
      weight = 3

      [[menu.main]]
      identifier = "identity"
      name = "Identity"
      url = "/about/identity/"
      parent = "about"
      weight = 4

      [[menu.main]]
      identifier = "resources"
      name = "Resources"
      url = "#"
      weight = 4
      hasChildren = true

      [[menu.main]]
      identifier = "download"
      name = "Download"
      url = "/resources/download/"
      parent = "resources"
      weight = 1

      [[menu.main]]
      identifier = "userguide"
      name = "Userguide"
      url = "/resources/userguide/"
      parent = "resources"
      weight = 2

      [[menu.main]]
      identifier = "workshops"
      name = "Workshops"
      url = "/resources/workshops/"
      parent = "resources"
      weight = 3

      [[menu.main]]
      identifier = "API"
      name = "API"
      url = "https://zoo-project.github.io/docs/C_API/"
      parent = "resources"
      weight = 4

      [[menu.main]]
      identifier = "examples"
      name = "Examples"
      url = "/resources/examples/"
      parent = "resources"
      weight = 5


      [[menu.main]]
      identifier = "presentation"
      name = "Presentation"
      url = "/resources/presentation/"
      parent = "resources"
      weight = 6



      [[menu.main]]
      identifier = "get-involved"
      name = "Get Involved"
      url = "#"
      weight = 5
      hasChildren = true


      [[menu.main]]
      identifier = "contributor-guide"
      name = "Contributor guide"
      url = "https://zoo-project.github.io/docs/contribute/index.html"
      parent = "get-involved"
      weight = 1

      [[menu.main]]
      identifier = "sponsorship"
      name = "Sponsorship"
      url = "/resources/sponsorship/"
      parent = "get-involved"
      weight = 2


      [[menu.main]]
      identifier = "knowledge_partners"
      name = "knowledge Partners"
      url = "/resources/knowledge_partners/"
      parent = "get-involved"
      weight = 3

      [[menu.main]]
      identifier = "feed_animals"
      name = "Feed Animals"
      url = "/resources/feed_animals/"
      parent = "get-involved"
      weight = 4


