baseURL = 'https://example.org'
languageCode = 'en-us'
theme = 'lugo'

[params]
description = 'The ZOO-Project is an open source processing platform, released under MIT/X11 Licence. It provides the polyglot ZOO-Kernel, a server implementation of the Web Processing Service (WPS) (1.0.0 and 2.0.0) and the OGC API - Processes standards published by the OGC'
primaryColor = "#55be55"
secondaryColor = "#142148"
textColor = "#ffffff"
textColorDark = "#142148"

# navigation
  [menu]
     [[menu.main]]
     identifier = "index"
      name = "Index"
      url = "/"
      weight = 1

    [[menu.main]]
      identifier = "about"
      name = "About"
      url = "#"
      weight = 2
      hasChildren = true

    [[menu.main]]
      identifier = "introduction"
      name = "Introduction"
      url = "https://zoo-project.github.io/docs/intro.html"
      parent = "about"
      weight = 3

     [[menu.main]]
      identifier = "tribe"
      name = "Tribe"
      url = "/about/tribe/"
      parent = "about"
      weight = 4

      [[menu.main]]
      identifier = "event"
      name = "Event"
      url = "/about/event/"
      parent = "about"
      weight = 5

      [[menu.main]]
      identifier = "identity"
      name = "Identity"
      url = "/about/identity/"
      parent = "about"
      weight = 6

